name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4  # 检出代码

      - name: Build the site in the ruby:4.4.4 container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          ruby:4.4.4 /bin/bash -c "
            gem install bundler jekyll &&  # 安装 Bundler 和 Jekyll
            bundle install &&             # 安装 Gemfile 中的依赖
            jekyll build --future         # 构建 Jekyll 站点
          "
